### ISSUE TITLE
Errors will occur when multiple special pieces are triggered

### ISSUE THREAD

**Issue by univeous** [ninetailsrabbit/match3-board#5]
Godot version: 4.4 dev4

**Describe the bug**
Errors will occur when multiple special pieces are triggered.
It can be reproduced stably.

**To Reproduce**

https://github.com/user-attachments/assets/aa248416-3d1a-48fc-8dbc-f24fb47ee416

**Comment by ninetailsrabbit** [comment]
Thanks for your time @univeous , I've been able to add instance checks in a few places including the one in your video to prevent the workflow from stopping when there is a large consumption of pieces in the board.

Further information in the [commit](https://github.com/ninetailsrabbit/match3-board/commit/e13eb9c0bd01a8ea30d7092e35a6e3b934d9eb75)

**Comment by univeous** [comment]
I can still reproduce this:

```GDscript
func _ready() -> void:
#...
	match_3_board.draw_piece_on_cell(match_3_board.get_cell_or_null(0, 0), SPECIAL_CROSS_PIECE.instantiate())
	match_3_board.draw_piece_on_cell(match_3_board.get_cell_or_null(0, 1), SPECIAL_CROSS_PIECE.instantiate())
	match_3_board.draw_piece_on_cell(match_3_board.get_cell_or_null(1, 1), SPECIAL_SHAPE_CONSUMER_PIECE.instantiate())
	match_3_board.remove_orphan_pieces()
#...
```

https://github.com/user-attachments/assets/0db62232-9560-4a52-91f1-1b7799ee4a35

**Comment by ninetailsrabbit** [comment]
@univeous It seems that the second special combo piece is not performing as it should, I'll look into it soon.

Seeing your way of drawing parts it would be nice to have a visual editor and new board methods to make this process easier.

I will see how to tackle this new feature, for now I have to work on other projects but I am writing it down as a pending task

Thanks for your time!
