### ISSUE TITLE
Add a method to spawn new piece in a specific position

### ISSUE THREAD

**Issue by univeous** [ninetailsrabbit/match3-board#7]
**Is your feature request related to a problem? Please describe.**
I hope to spawn special pieces at the position where the pieces are swapped;

Currently, I am using the following code to implement this:
```GDScript
# demo.gd 

func _ready() -> void:
	# ...
	var consumer := DemoSequenceConsumer.new()
	match_3_board.change_sequence_consumer(consumer)
	match_3_board.state_changed.connect(on_state_changed)
	match_3_board.swap_requested.connect(func(from: PieceUI, to: PieceUI):
		consumer.recently_swapped = [from, to]
	)
	# ...
```

```GDScript
# demo_sequence_consumer.gd
# ...
var recently_swapped:Array[PieceUI] = []


func detect_new_combined_piece(sequence: Sequence):
	if sequence.all_pieces_are_of_type(PieceConfiguration.PieceType.Normal) \
		and (sequence.is_horizontal_or_vertical_shape() or sequence.is_tshape_or_lshape()):
			match sequence.size():
				4:
					var new_special_piece: SpecialCrossPiece = SpecialCrossPieceScene.instantiate() as SpecialCrossPiece
					for piece: PieceUI in sequence.pieces():
						if piece in recently_swapped:
							recently_swapped.erase(piece)
							var cell := piece.cell()
							new_special_piece.set_meta("cell", cell)
							break
					return new_special_piece
# ...
```

```GDScript
# sequence_consumer.gd
# ...
class DrawNewPieceSequenceAction extends SequenceAction:
	func run() -> void:
		var target_cell_to_spawn: GridCellUI = sequence.middle_cell()
		if arguments.new_piece.has_meta("cell"):
			target_cell_to_spawn = arguments.new_piece.get_meta("cell")
			arguments.new_piece.set_meta("cell", null)
		
		await consumer.board.piece_animator.consume_pieces(sequence.normal_pieces())
		
		sequence.consume_only_normal_pieces()

		consumer.board.draw_piece_on_cell(target_cell_to_spawn, arguments.new_piece)
		await consumer.board.piece_animator.spawn_special_piece(target_cell_to_spawn, arguments.new_piece)
#...
```
This can work normally, although it may look a bit hacky.

My only complaint is that it requires me to modify the `sequence_consumer.gd` in the plugin, and I really don't want to do that.

Can you come up with a better way to achieve this? :)

**Comment by ninetailsrabbit** [comment]
@univeous You're right, it looks a bit tricky and really the end user **shouldn't have to modify the inner classes.**

I've created a simple approach with a new overridable method in `PieceUI `that allows you to create your own custom logic to generate and draw parts, further information in this [commit](https://github.com/ninetailsrabbit/match3-board/commit/bd412a561f0bd0ae4fe231f39d9c48a1fa63275e).

I have created a dictionary as an argument in case more parameters are needed in the future. At the moment it only receives the `Sequence` to which it belongs.


### The new overridable method in PieceUI
```swift
func custom_spawn_and_draw(arguments: Dictionary = {}):
	return null
```

### A simple example
This logic spawn the new special piece in a random cell replacing the previous one:

```swift
func custom_spawn_and_draw(arguments: Dictionary = {}):
	var random_cell: GridCellUI = board.grid_cells_flattened.pick_random() as GridCellUI
	var previous_piece: PieceUI = random_cell.replace_piece(self)
	
	if previous_piece:
		previous_piece.queue_free()
	
	return random_cell
```

### In case no custom logic is defined and null is returned
In this particular case all works as before, creating the new special piece in the middle cell of the origin sequence
